<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détail de la tâche</title>
</head>
<body>
    <h1><?php echo $task['title'] ?></h1>
    <p><?php echo $task['description'] ?></p>
    <p>A faire avant le : <?php echo $date ?></p>
    <p><a href="?route=delete&id=<?php echo $task['id'] ?>">❌</a></p>
    <a href="?route=index">Retour à l'accueil</a>
</body>
</html>