<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Enregistrement</title>
</head>
<body>
    <h1>Enregistrement</h1>
    <form action="" method="post">
        Nom <input type="text" name="name" value="<?php echo $name ?>" required><br>
        Mot de passe <input type="password" name="pwd" required><br>
        Vérification du mot de passe <input type="password" name="pwdVerif"  required><br>
        <?php echo $error . '<br>'; ?>
        <input type="submit" value="Enregistrement">
        <tex></tex>
    </form>
    <p><a href="/">Retour à l'accueil</a></p></body>
</html>