server {
    listen 80;
    
    root /var/www/html/public;
    
    index index.php index.html;

    # Pour toutes les URLs (/, /contact, etc.)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Uniquement index.php est exécuté directement
    location ~ ^/index\.php(/|$) {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        internal;
    }

    # Tous les autres .php sont bloqués
    location ~ \.php$ {
        return 404;
    }
}