<?php $title = 'Description' ?>

<?php ob_start() ?>

<h1><?= htmlspecialchars($book->getTitle()) ?></h1>
<p>Auteur : <?= htmlspecialchars($book->getAuthor()) ?></p>
<p>Description : <br> <?= htmlspecialchars($book->getDescription()) ?></p>
<form action="?route=borrow" method="post">
    <input type="hidden" name="id_book" value="<?= $book->getId() ?>">
    <label for="user">Nom de l'emprunteur</label>
    <input type="text" name="user" required> <input type="submit" value="Emprunter">
</form>

<?php $content = ob_get_clean() ?>

<?php require 'src/view/base.phtml' ?>
