<?php $title = 'Accueil'; ?>

<?php ob_start() ?>
    <h1>Classe</h1>
    <ul>
        <?php foreach ($users as $user) { 
            /** @var Notes\App\Entity\User $user */
        ?>
            <li>
                <?= ucfirst(htmlspecialchars($user->getLastname())) ?> <?= ucfirst(htmlspecialchars($user->getFirstname())) ?> 
                <a href="?route=show&id=<?= $user->getId() ?>">📓</a>
            </li>
        <?php } ?>
    </ul>


<?php $content = ob_get_clean(); ?>

<?php require 'src/view/base.phtml' ?>

