<?php $title = '' ?>

<?php ob_start() ?>
    <h1>Modifier le bulletin</h1>

    <form action="?route=update" method="post">
        <label for="comment">Commentaires :</label><br>
        <textarea name="comment" cols="80" rows="5" required><?= $appreciation->getComment() ?></textarea><br>
        
        <legend>Mention :</legend><br>
        <input type="radio" name="mention" value="Avertissement" 
        <?= $appreciation->getMention() === 'Avertissement' ? 'checked' : '' ?>>
        <label for="Avertissement">Avertissement</label>
        <input type="radio" name="mention" value="Encouragements" 
        <?= $appreciation->getMention() === 'Encouragements' ? 'checked' : '' ?>>
        <label for="Encouragements">Encouragements</label>
        <input type="radio" name="mention" value="Felicitations" 
        <?= $appreciation->getMention() === 'Felicitations' ? 'checked' : '' ?>>
        <label for="Felicitations">Félicitations</label><br>
        <input type="hidden" name="id_user" value="<?= $appreciation->getId_user() ?>">
        <input type="submit" value="Modifier">
    </form>

    <p><a href="?route=show&id=<?= $appreciation->getId_user() ?>">Retour à l'élève</a></p>
<?php $content = ob_get_clean() ?>

<?php require 'src/view/base.phtml'; ?>