<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
</head>
<body>
    <?php if (isset($_SESSION['user'])) { ?>
        <p><a href="?route=deconnection">Deconnexion</a></p>
    <?php } else { ?>
        <p><a href="?route=register">Enregistrement</a> / <a href="?route=connection">Connexion</a></p>
    <?php } ?>
</body>
</html>
