<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Plannifcateur de tâche</title>
</head>
<body>
    <h1>Mes tâches</h1>
  
    <ul>
        <?php foreach($tasks as $task) { ?>
        <li>
            <a href="?route=change&id=<?php echo $task->getId() ?>&is_done=<?php echo $task->getIs_done() ?>"><?php echo $task->getIconStatus() ?></a> 
            <?php echo htmlspecialchars($task->getTitle()) ?> - <?php echo $task->getFormatedDeadline() ?> - 
            <a href="?route=show&id=<?php echo $task->getId() ?>">voir le détail</a>
        </li>
        <?php } ?>
    </ul>
</body>
</html>