<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil</title>
</head>
<body>
    <h1>Liste des livres</h1>
    <form action="?route=search">
        <input type="text" name="author" placeholder="Chercher un auteur">
        <input type="submit" value="🔎">
    </form>
    <ul>
        <?php foreach ($books as $book) {?>
        <li><?= htmlspecialchars($book->getTitle()) ?> <a href="?route=show&id=<?php echo $book->getId() ?>">📋</a></li>
        <?php } ?>
    </ul>
    
</body>
</html>