<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Création d'un mot de passe</title>
</head>
<body>
    <h1>Ajouter un mot de passe</h1>
    <form action="?route=add" method="post">
        <label for="title">Titre du mot de passe <input type="text" name="title"></label>
        <br>
        <label for="secret">Mot de passe <input type="text" name="secret"></label>
        <br>
        <input type="submit" value="Ajouter"> <?php echo $error ?>
    </form>
    <p><a href="index.php">Retour à l'accueil</a></p>
</body>
</html>