<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liste de courses</title>
</head>
<body>
    <h1>Liste de courses :</h1>
    <form action="src/add.php" method="post">
        <label for="product">Produit : </label>
        <input type="text" name="item">
        <input type="hidden" name="token_csrf" value="<?php echo $tokenCsrf ?>">
        <input type="submit" value="Ajouter">
    </form>
    <ul>
        <?php foreach ($products as $product) { ?>
        <li>
            <?php echo htmlspecialchars($product['name']) ?>
            <a href="src/delete.php?id=<?php echo $product['id'] ?>&token_csrf=<?php echo $tokenCsrf ?>" onclick="return deleteConfirmation()">❌</a>      
            <a href="src/update.php?id=<?php echo $product['id'] ?>">✏️</a>
        </li>
        <?php } ?>
    </ul>
    <script>
        function deleteConfirmation() {
            return confirm('Etes-vous sûr de vouloir supprimmer ce produit de la liste ?');
        }
    </script>
</body>
</html>