<?php $title = 'Modification d\'un contact'; ?>

<?php ob_start() ?>

<h1>Modifier un contact</h1>

<form action="?route=update&id=<?= $contact->getId() ?>" method="post">
    <label for="nom">Nom</label> <input type="text" name="nom" value="<?= $contact->getNom() ?>"><br>
    <label for="prenom">Prénom</label> <input type="text" name="prenom" value="<?= $contact->getPrenom() ?>"><br>
    <label for="email">Courriel</label> <input type="email" name="email" value="<?= $contact->getEmail() ?>"><br>
    <label for="telephone">Téléphone</label> <input type="phone" name="telephone" value="<?= $contact->getTelephone() ?>"><br>
    <label for="adresse">Adresse</label> <input type="text" name="adresse" value="<?= $contact->getAdresse() ?>"><br>    
    <input type="submit" value="Modifier">
</form>

<?php $content = ob_get_clean() ?>

<?php require 'src/view/base.phtml' ?>