<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Connexion</h1>
    <form action="" method="post">
        Nom <input type="text" name="name" required> <br>
        Mot de passe <input type="password" name="pwd" rquired><br>
        <input type="submit" value="Connexion"> <?php echo $message ?>
    </form>
    <p><a href="/">Retour à l'accueil</a></p>
</body>
</html>